name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop


jobs:
  check-application:
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    go: [ '1.14', '1.15' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up DockerBuildx
        uses: docker/setup-buildx-action@v1
      
      #- name: Login to DockerHub

      - name: Build and push
        id: docker_build # podemos pegar o resultado e usar em uma outra step usando id
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: angolar/fc2-ci-go:latest